### ISSUE TITLE
Generator taking too long to prompt for user input

### ISSUE THREAD

**Issue by Zarmeena** [lamartire/generator-cucumber-steps#1]
It is a very useful utility for automated step definition creation but I am facing the following issue:
On issuing 'yo cucumber-steps' command, it is taking too long to ask for the user input. Please suggest the resolution or any other way of invoking this generator.

**Comment by epszaw** [comment]
Hello and thanks for your issue. I did really think – it is useful only for me 🙂
So, I will fix some things and rewrite in a few days (may be weeks 😄) and notify you! 🙌

**Comment by Zarmeena** [comment]
Thanks for your response...Could you also please provide a way of passing the feature file name and step definition path instead of asking for the user to prompt . I need to invoke it from another method and not directly from terminal.
Thanks!

**Comment by epszaw** [comment]
@Zarmeena what do you expect? Can you tell more about?

**Comment by Zarmeena** [comment]
Hi Lamartire,
We are working on creating a cucumber based testing framework where in we want automated creation of step definitions for feature files.
Following are my requirements:
1. Invocation of 'yo cucumber-steps' command from another parent function along with a callback.
 
Issue: Currently, I have tried executing this command from terminal itself and another method as well but it is taking too long to prompt for the user input, although the generated step defs is completely fine.

2. Parameterized call of underlying 'writing' method of your utility.The two parameters should be feature file name and stepdefs path.

Issue: Currently, the feature file name and scenario is taken from user input from the terminal. I want parameters to be passed to 'writing' method.

**Comment by epszaw** [comment]
@Zarmeena, so, I can move that funtionality to external library and reuse it in the generator. I can do that in the generator because it does not fit to the yeoman conception, imo. It is not difficult, I will notify you here.

**Comment by Zarmeena** [comment]
Sure lamartire...Thank you so much!

**Comment by Zarmeena** [comment]
Hi Lamartire..Do we have any update on this?

**Comment by epszaw** [comment]
Hello! Sorry, but not :(
I promise - I will implement that especially for you! 😉

сб, 15 июн. 2019 г., 9:20 Zarmeena <notifications@github.com>:

**Comment by epszaw** [comment]
@Zarmeena hey there! I've done it.
Try to use [](https://github.com/lamartire/cucumber-steps-defs). There are bin and programmatically way to generate steps.
Leave your feedback and issues in the new project!
Have a nice day!

**Comment by Zarmeena** [comment]
Thanks for your help Lamartire !
